// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/layouts/default/AppBar.vue')['default']
    Button: typeof import('./src/components/styled/Button.ts')['default']
    Default: typeof import('./src/layouts/default/Default.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    View: typeof import('./src/layouts/default/View.vue')['default']
  }
}

export { }
